#undef RGBLIGHT_ANIMATIONS
#undef LOCKING_SUPPORT_ENABLE
#undef LOCKING_RESYNC_ENABLE

#define MOUSEKEY_DELAY 66
#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_WHEEL_DELAY 66
#define MOUSEKEY_WHEEL_INTERVAL 16

#undef BACKLIGHT_LEVELS
#undef RGBLIGHT_HUE_STEP
#undef RGBLIGHT_SAT_STEP
#define BACKLIGHT_LEVELS 31
#define RGBLIGHT_HUE_STEP 3
#define RGBLIGHT_SAT_STEP 5

